spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000
      pool-name: ReservationHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  h2:
    console:
      enabled: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.azki.reservationsystem: INFO
    org.hibernate.SQL: WARN
