name: azki-reservation-system

services:
  mysql:
    image: mysql:8.4
    container_name: azki-mysql
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${MYSQL_PORT:-3306}:3306"

    command:
      - --innodb-buffer-pool-size=256M
      - --max-connections=200

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  mysql-test:
    image: mysql:8.4
    container_name: azki-mysql-test
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: azki_reservations_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    command:
      - --innodb-buffer-pool-size=256M
      - --max-connections=200

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: azki-redis
    restart: unless-stopped

    ports:
      - "${REDIS_PORT:-6379}:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis-test:
    image: redis:7-alpine
    container_name: azki-redis-test
    restart: unless-stopped

    ports:
      - "6380:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  app:
    container_name: azki-reservation

    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "${APP_PORT:-8080}:8080"

volumes:
  mysql_data:
  mysql_test_data: